/*
 * ADC_program.c
 *
 * Created: 2/15/2025 3:01:04 PM
 *  Author: Ahmad abdullatif
 */
#include "std_types.h"
#include "bit_math.h"
#include "ADC_interface.h"
#include "ADC_registers.h"
#include "DIO_interface.h"


void ADC_voidInit(u8 copy_u8VrefType){
	switch(copy_u8VrefType){
		case ADC_AREF:
		CLEAR_BIT(ADMUX_REGISTER,ADC_REFS0_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_REFS1_BIT);
		break;
		case ADC_AVCC:
		SET_BIT  (ADMUX_REGISTER,ADC_REFS0_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_REFS1_BIT);
		break;
		case ADC_INTERNAL_VREF:
		SET_BIT  (ADMUX_REGISTER,ADC_REFS0_BIT);
		SET_BIT  (ADMUX_REGISTER,ADC_REFS1_BIT);
		break;
	}
	//choosing right adjustment 
	CLEAR_BIT(ADMUX_REGISTER,ADC_ADLAR_BIT);
	
	//enable ADC
	SET_BIT  (ADCSRA_REGISTER,ADC_ADEN_BIT);
	
	//disable auto trigger
	CLEAR_BIT(ADCSRA_REGISTER,ADC_ADATE_BIT);
	
	//disable ADC interrupt
	CLEAR_BIT(ADCSRA_REGISTER,ADC_ADIE_BIT);
	
	//setting prescaler to /128
	SET_BIT(ADCSRA_REGISTER,ADC_ADPS2_BIT);
	SET_BIT(ADCSRA_REGISTER,ADC_ADPS1_BIT);
	SET_BIT(ADCSRA_REGISTER,ADC_ADPS0_BIT);
	
}
u16  ADC_u16GetAdcResult(u8 copy_u8AdcChannelId){
	switch(copy_u8AdcChannelId){
		case ADC_ADC0:
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX0_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX1_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX2_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX3_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX4_BIT);
		DIO_voidSetPinDirection(DIO_PORTA,DIO_PIN0,DIO_INPUT);
		break;
		case ADC_ADC1:
		SET_BIT  (ADMUX_REGISTER,ADC_MUX0_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX1_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX2_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX3_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX4_BIT);
		DIO_voidSetPinDirection(DIO_PORTA,DIO_PIN1,DIO_INPUT);
		break;
		case ADC_ADC2:
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX0_BIT);
		SET_BIT  (ADMUX_REGISTER,ADC_MUX1_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX2_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX3_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX4_BIT);
		DIO_voidSetPinDirection(DIO_PORTA,DIO_PIN2,DIO_INPUT);
		break;
		case ADC_ADC3:
		SET_BIT  (ADMUX_REGISTER,ADC_MUX0_BIT);
		SET_BIT  (ADMUX_REGISTER,ADC_MUX1_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX2_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX3_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX4_BIT);
		DIO_voidSetPinDirection(DIO_PORTA,DIO_PIN3,DIO_INPUT);
		break;
		case ADC_ADC4:
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX0_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX1_BIT);
		SET_BIT  (ADMUX_REGISTER,ADC_MUX2_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX3_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX4_BIT);
		DIO_voidSetPinDirection(DIO_PORTA,DIO_PIN4,DIO_INPUT);
		break;
		case ADC_ADC5:
		SET_BIT  (ADMUX_REGISTER,ADC_MUX0_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX1_BIT);
		SET_BIT  (ADMUX_REGISTER,ADC_MUX2_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX3_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX4_BIT);
		DIO_voidSetPinDirection(DIO_PORTA,DIO_PIN5,DIO_INPUT);
		break;
		case ADC_ADC6:
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX0_BIT);
		SET_BIT  (ADMUX_REGISTER,ADC_MUX1_BIT);
		SET_BIT  (ADMUX_REGISTER,ADC_MUX2_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX3_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX4_BIT);
		DIO_voidSetPinDirection(DIO_PORTA,DIO_PIN6,DIO_INPUT);
		break;
		case ADC_ADC7:
		SET_BIT  (ADMUX_REGISTER,ADC_MUX0_BIT);
		SET_BIT  (ADMUX_REGISTER,ADC_MUX1_BIT);
		SET_BIT  (ADMUX_REGISTER,ADC_MUX2_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX3_BIT);
		CLEAR_BIT(ADMUX_REGISTER,ADC_MUX4_BIT);
		DIO_voidSetPinDirection(DIO_PORTA,DIO_PIN7,DIO_INPUT);
		break;
	}
	//start conversion
	SET_BIT(ADCSRA_REGISTER,ADC_ADSC_BIT);
	
	//busy wait for the conversion to be done
	while(GET_BIT(ADCSRA_REGISTER,ADC_ADIF_BIT) == 0);
	
	//clearing the flag manually
	SET_BIT(ADCSRA_REGISTER,ADC_ADIF_BIT);
	
	//returning result
	return (u16)ADC_DATA_REGISTER;
}
