/*
 * i2c_private.h
 *
 * Created: 11/3/2025 8:12:28 AM
 *  Author: Ahmad Abdullatif
 */


#ifndef I2C_PRIVATE_H_
#define I2C_PRIVATE_H_

#define I2C_STATUS_CODE_VALUE                             (TWSR_REG & 0b11111000)
#define I2C_STATUS_CODE_START_CONDITION_SENT              (0x08)
#define I2C_STATUS_CODE_REPEATED_START_CONDITION_SENT     (0x10)
#define I2C_STATUS_CODE_SLAVE_ADDRESS_WRITE_SENT_WITH_ACK (0X18)
#define I2C_STATUS_CODE_SLAVE_ADDRESS_READ_SENT_WITH_ACK  (0X40)
#define I2C_STATUS_CODE_BYTE_DATA_SENT_WITH_ACK           (0X28)
#define I2C_STATUS_CODE_BYTE_DATA_RECEIVED_WITH_ACK       (0X50)
#define I2C_STATUS_CODE_BYTE_DATA_RECEIVED_WITHOUT_ACK    (0X58)

#endif /* I2C_PRIVATE_H_ */
